services:
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - $CONFIGDIR/Calibre:/config
        
      - $BOOKDIR/library:/books
    ports:
      - $CALIBRE_8080_PORT:8080
      - $CALIBRE_8081_PORT:8081
    restart: unless-stopped
