services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SUBFOLDER=/ #optional
    volumes:
      - $CONFIGDIR/emulatorjs:/config
      - $ROMSDIR:/data
    ports:
      - $EMULATORJS_3000_PORT:3000
      - $EMULATORJS_80_PORT:80
      - $EMULATORJS_4001_PORT:4001 #optional
    restart: unless-stopped